version: '3'

services: 
  web:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/code
    depends_on: 
      - db
  
  db:
    image: postgres
    ports: 
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres/data 
    environment: 
      POSTGRES_HOST_AUTH_METHOD: "trust"
      
volumes:
  dbdata: