version: '3'

services: 
  web:
    build: .
    ports:
      - "3333:3333"
    command: sh ./docker-start.sh
    volumes:
      - .:/home/app
      - /home/app/node_modules
    depends_on: 
      - db
  
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
